# Generated by Django 3.2.8 on 2021-11-15 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashier',
            options={'verbose_name': 'кассира', 'verbose_name_plural': 'кассиры'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'продукт с размером', 'verbose_name_plural': 'продукты с размерами'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'тип продукта', 'verbose_name_plural': 'типы продуктов'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'продажу', 'verbose_name_plural': 'продажи'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'сезон', 'verbose_name_plural': 'сезоны'},
        ),
        migrations.AlterField(
            model_name='cashier',
            name='cashier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='кассир'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='end_day',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='последний день'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='запрлата'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='start_day',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='первый день'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_price',
            field=models.IntegerField(verbose_name='начальная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='markup',
            field=models.IntegerField(verbose_name='накрутка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_after_markup',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена после накрутки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.season', verbose_name='сезон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producttype', verbose_name='тип продукта'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='count',
            field=models.IntegerField(default=0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.IntegerField(default=0, verbose_name='размер'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='кассир'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(verbose_name='время продажи'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='discount_type',
            field=models.CharField(choices=[('amount', 'Сумма'), ('percentage', 'Процент'), ('none', 'Без скидки')], default='none', max_length=16, verbose_name='тип скидки'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='last_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='окончательная цена'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='net_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='чистая прибыль'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.productsize', verbose_name='продукт с размером'),
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
    ]
