# Generated by Django 3.2.8 on 2021-11-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211115_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(max_length=255, null=True, verbose_name='качество'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='count',
            field=models.IntegerField(null=True, verbose_name='количество'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_sum',
            field=models.IntegerField(null=True, verbose_name='общая сумма'),
        ),
    ]
