# Generated by Django 3.2.8 on 2021-11-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211117_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='качество'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='общая сумма'),
        ),
    ]
