# Generated by Django 3.2.8 on 2021-11-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211117_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='count',
            field=models.IntegerField(null=True, verbose_name='количество'),
        ),
    ]
